#!/usr/bin/env bash
# sign-user-key.sh — Issue an SSH certificate for one or more Forgejo users.
#
# Single-user mode:
#   ./sign-user-key.sh <forgejo-username> <user-public-key-file>
#
# Batch mode:
#   ./sign-user-key.sh --batch <csv-file> [options]
#
# CSV format (one user per line; blank lines and # comments ignored;
#             optional header "username,key" is skipped):
#   username
#   username,/path/to/key.pub
#   username,ssh-ed25519 AAAA...
#   (no key column → ed25519 keypair is auto-generated for that user)
#
# Batch options:
#   --output-dir DIR    Write keys and certs here (default: ./keys)
#   --forgejo-url URL   Forgejo base URL (default: https://<terraform output ip>)
#   --admin-token TOK   Forgejo admin API token (default: auto-generated via SSH)
#   --no-register       Sign certs only; skip Forgejo user/key registration
#
# Environment overrides: FORGEJO_URL, FORGEJO_ADMIN_TOKEN, ADMIN_SSH_KEY, CERT_VALIDITY
#
# Requires:
#   - Yubikey with SSH CA key in PIV slot 9d (generated by setup.sh)
#   - ca.pub (SSH-format CA public key, written by setup.sh)
#   - .ykcs11_lib (PKCS#11 library path, written by setup.sh)
#
# Single-user produces: <user-pubkey-file>-cert.pub
# Batch produces:       keys/<username>/{id_ed25519,id_ed25519.pub,id_ed25519-cert.pub}
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()   { echo -e "${GREEN}[sign]${NC} $*"; }
warn()   { echo -e "${YELLOW}[sign]${NC} $*"; }
error()  { echo -e "${RED}[sign]${NC} $*" >&2; exit 1; }
header() { echo -e "${CYAN}[sign]${NC} $*"; }

# ── Common prerequisites ───────────────────────────────────────────────────────
[ -f ca.pub ]      || error "ca.pub not found. Run setup.sh first."
[ -f .ykcs11_lib ] || error ".ykcs11_lib not found. Run setup.sh first."

PKCS11_LIB="$(cat .ykcs11_lib)"
[ -f "$PKCS11_LIB" ] || error "PKCS#11 library not found: $PKCS11_LIB"
ykman info &>/dev/null || error "No Yubikey detected. Connect your Yubikey and try again."

VALIDITY="${CERT_VALIDITY:-+365d}"

# ── JSON helper (builds a properly-escaped JSON string value) ─────────────────
json_str() { python3 -c "import sys,json; print(json.dumps(sys.stdin.read().strip()))"; }

# ── Single-user mode ──────────────────────────────────────────────────────────
if [[ "${1:-}" != "--batch" ]]; then
    [ "$#" -eq 2 ] || error "Usage: $0 <forgejo-username> <user-public-key-file>
       $0 --batch <csv-file> [--output-dir DIR] [--forgejo-url URL]
                             [--admin-token TOKEN] [--no-register]"
    USERNAME="$1"
    USER_PUBKEY="$2"
    [ -f "$USER_PUBKEY" ] || error "Public key file not found: $USER_PUBKEY"

    info "Signing public key for Forgejo user '$USERNAME' (validity: $VALIDITY)"
    # Principal must be 'git' (the Unix login user for all Forgejo SSH connections).
    # The Forgejo user is identified by the registered base public key via
    # AuthorizedKeysCommand, not by the cert principal.
    info "Principal: git (Unix login user)"
    info "Key file:  $USER_PUBKEY"
    echo

    info "Waiting for Yubikey touch/PIN (you may be prompted up to twice)..."
    ssh-keygen \
        -s ca.pub \
        -D "$PKCS11_LIB" \
        -I "${USERNAME}@forgejo" \
        -n "git" \
        -V "$VALIDITY" \
        "$USER_PUBKEY"

    CERT_FILE="${USER_PUBKEY%.*}-cert.pub"
    if [ ! -f "$CERT_FILE" ]; then
        CERT_FILE="${USER_PUBKEY}-cert.pub"
    fi
    [ -f "$CERT_FILE" ] || error "Certificate file not found after signing. Check ssh-keygen output above."

    echo
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    info "Certificate issued: $CERT_FILE"
    echo "  Fingerprint: $(ssh-keygen -l -f "$CERT_FILE")"
    echo
    echo "  Instructions for '$USERNAME':"
    echo "    1. Place $CERT_FILE alongside your private key"
    echo "       (e.g. ~/.ssh/id_ed25519-cert.pub if key is ~/.ssh/id_ed25519)"
    echo "       SSH picks it up automatically — no config change needed."
    echo "    2. Ensure your raw public key is registered in Forgejo"
    echo "       (Settings → SSH / GPG Keys → Add Key)."
    echo "    3. Clone with:  git clone git@\$DOMAIN:2222/user/repo.git"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    exit 0
fi

# ── Batch mode ────────────────────────────────────────────────────────────────
shift  # consume --batch
[ $# -ge 1 ] || error "Usage: $0 --batch <csv-file> [options]"
BATCH_CSV="$1"; shift
[ -f "$BATCH_CSV" ] || error "CSV file not found: $BATCH_CSV"

OUTPUT_DIR="./keys"
FORGEJO_URL="${FORGEJO_URL:-}"
ADMIN_TOKEN="${FORGEJO_ADMIN_TOKEN:-}"
REGISTER=true

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output-dir)  OUTPUT_DIR="$2"; shift 2 ;;
        --forgejo-url) FORGEJO_URL="$2"; shift 2 ;;
        --admin-token) ADMIN_TOKEN="$2"; shift 2 ;;
        --no-register) REGISTER=false; shift ;;
        *) error "Unknown option: $1" ;;
    esac
done

mkdir -p "$OUTPUT_DIR"

# ── Parse CSV ─────────────────────────────────────────────────────────────────
header "Parsing $BATCH_CSV..."

declare -a USERNAMES=()
declare -a KEY_SOURCES=()

while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line//$'\r'/}"                    # strip Windows CR
    [[ -z "$line" || "$line" == \#* ]] && continue

    username="${line%%,*}"
    username="${username//[[:space:]]/}"      # strip all whitespace
    [[ -z "$username" || "${username,,}" == "username" ]] && continue

    if [[ "$line" == *,* ]]; then
        key_col="${line#*,}"
        # strip leading and trailing whitespace
        key_col="${key_col#"${key_col%%[![:space:]]*}"}"
        key_col="${key_col%"${key_col##*[![:space:]]}"}"
    else
        key_col=""
    fi

    USERNAMES+=("$username")
    KEY_SOURCES+=("$key_col")
done < "$BATCH_CSV"

[ ${#USERNAMES[@]} -gt 0 ] || error "No users found in $BATCH_CSV"
info "Found ${#USERNAMES[@]} user(s): ${USERNAMES[*]}"
echo

# ── Resolve or generate public keys ───────────────────────────────────────────
header "Preparing public keys..."

declare -a PUBKEY_FILES=()
declare -a IS_AUTO_GENERATED=()

for i in "${!USERNAMES[@]}"; do
    username="${USERNAMES[$i]}"
    key_src="${KEY_SOURCES[$i]}"
    user_dir="$OUTPUT_DIR/$username"
    mkdir -p "$user_dir"

    if [[ -z "$key_src" ]]; then
        # Auto-generate ed25519 keypair
        priv="$user_dir/id_ed25519"
        pub="${priv}.pub"
        if [[ -f "$pub" ]]; then
            warn "  $username: reusing existing key at $pub"
        else
            ssh-keygen -t ed25519 -N "" -C "${username}@forgejo" -f "$priv" -q
            chmod 600 "$priv"
            info "  $username: generated ed25519 keypair → $priv"
        fi
        PUBKEY_FILES+=("$pub")
        IS_AUTO_GENERATED+=(true)

    elif [[ "$key_src" == ssh-* || "$key_src" == ecdsa-* || "$key_src" == sk-* ]]; then
        # Inline SSH public key string
        pub="$user_dir/authorized_key.pub"
        echo "$key_src" > "$pub"
        info "  $username: using provided SSH public key"
        PUBKEY_FILES+=("$pub")
        IS_AUTO_GENERATED+=(false)

    elif [[ -f "$key_src" ]]; then
        # Path to an existing .pub file
        info "  $username: using key file $key_src"
        PUBKEY_FILES+=("$key_src")
        IS_AUTO_GENERATED+=(false)

    else
        warn "  $username: key source not found or unrecognized: '$key_src' — skipping"
        PUBKEY_FILES+=("")
        IS_AUTO_GENERATED+=(false)
    fi
done

echo

# ── Sign all keys with Yubikey ────────────────────────────────────────────────
VALID_COUNT=0
for pf in "${PUBKEY_FILES[@]}"; do [[ -n "$pf" ]] && VALID_COUNT=$((VALID_COUNT + 1)); done

header "Signing $VALID_COUNT key(s) with Yubikey (validity: $VALIDITY)"
warn "Touch is cached for 15 s — you may need to touch the Yubikey multiple times."
echo

declare -a CERT_FILES=()
declare -a SIGN_FAILED=()

for i in "${!USERNAMES[@]}"; do
    username="${USERNAMES[$i]}"
    pubkey="${PUBKEY_FILES[$i]}"

    if [[ -z "$pubkey" ]]; then
        CERT_FILES+=("")
        continue
    fi

    user_dir="$OUTPUT_DIR/$username"
    pub_basename="$(basename "$pubkey")"
    local_pub="$user_dir/$pub_basename"

    # Ensure the pubkey lives in user_dir so the cert is written there
    [[ "$pubkey" != "$local_pub" ]] && cp "$pubkey" "$local_pub"

    info "  Signing '$username'..."
    if ssh-keygen \
            -s ca.pub \
            -D "$PKCS11_LIB" \
            -I "${username}@forgejo" \
            -n "git" \
            -V "$VALIDITY" \
            "$local_pub" 2>&1; then

        # ssh-keygen appends -cert.pub after stripping the existing extension
        expected="${local_pub%.*}-cert.pub"
        [[ -f "$expected" ]] || expected="${local_pub}-cert.pub"

        if [[ -f "$expected" ]]; then
            CERT_FILES+=("$expected")
            info "  ✓ $username → $(basename "$expected")"
        else
            warn "  ✗ $username: cert not found after signing"
            CERT_FILES+=("")
            SIGN_FAILED+=("$username")
        fi
    else
        warn "  ✗ $username: ssh-keygen failed"
        CERT_FILES+=("")
        SIGN_FAILED+=("$username")
    fi
done

echo

# ── Register in Forgejo ───────────────────────────────────────────────────────
declare -a REGISTER_FAILED=()

if $REGISTER; then
    # Resolve Forgejo URL
    if [[ -z "$FORGEJO_URL" ]]; then
        if command -v terraform &>/dev/null && [[ -d "$SCRIPT_DIR/terraform" ]]; then
            _ip="$(cd "$SCRIPT_DIR/terraform" && terraform output -raw public_ipv4 2>/dev/null || true)"
            [[ -n "$_ip" ]] && FORGEJO_URL="https://${_ip}"
        fi
        [[ -n "$FORGEJO_URL" ]] \
            || error "Cannot determine Forgejo URL. Pass --forgejo-url URL or set FORGEJO_URL."
        info "Forgejo URL (from Terraform): $FORGEJO_URL"
    fi

    # Resolve admin token
    if [[ -z "$ADMIN_TOKEN" ]]; then
        _ip="${FORGEJO_URL#https://}"; _ip="${_ip#http://}"; _ip="${_ip%%/*}"

        _admin_user="gitadmin"
        if [[ -f "$SCRIPT_DIR/.vault.token" ]]; then
            export VAULT_ADDR="http://127.0.0.1:8200"
            export VAULT_TOKEN="$(cat "$SCRIPT_DIR/.vault.token")"
            if vault status &>/dev/null 2>&1; then
                _vu="$(vault kv get -field=forgejo_admin_user secret/forgejo/deploy 2>/dev/null || true)"
                [[ -n "$_vu" ]] && _admin_user="$_vu"
            fi
        fi

        _ssh_key="${ADMIN_SSH_KEY:-$HOME/.ssh/id_ed25519}"
        _kh="$SCRIPT_DIR/known_hosts.deploy"
        _ssh_opts="-i $_ssh_key -o ConnectTimeout=15 -o BatchMode=yes"
        [[ -f "$_kh" ]] \
            && _ssh_opts="$_ssh_opts -o UserKnownHostsFile=$_kh -o StrictHostKeyChecking=yes" \
            || _ssh_opts="$_ssh_opts -o StrictHostKeyChecking=no"

        info "Generating admin API token via SSH (admin user: $_admin_user)..."
        ADMIN_TOKEN="$(ssh $_ssh_opts "root@$_ip" \
            "docker exec -u git forgejo /usr/local/bin/forgejo admin user \
             generate-access-token --username $_admin_user \
             --token-name batch-sign-$(date +%s) --raw 2>&1" 2>/dev/null || true)"

        [[ -n "$ADMIN_TOKEN" ]] \
            || error "Could not obtain admin token. Pass --admin-token TOKEN or set FORGEJO_ADMIN_TOKEN."
        info "Admin token obtained."
    fi

    _domain="${FORGEJO_URL#https://}"; _domain="${_domain#http://}"; _domain="${_domain%%/*}"
    echo
    header "Registering in Forgejo ($FORGEJO_URL)..."
    echo

    for i in "${!USERNAMES[@]}"; do
        username="${USERNAMES[$i]}"
        pubkey="${PUBKEY_FILES[$i]}"
        cert="${CERT_FILES[$i]}"

        [[ -n "$pubkey" && -n "$cert" ]] || continue

        info "  ── $username"

        # Create user if not present
        _status="$(curl -sk -o /dev/null -w '%{http_code}' \
            -H "Authorization: token $ADMIN_TOKEN" \
            "$FORGEJO_URL/api/v1/users/$username" || true)"

        if [[ "$_status" == "404" ]]; then
            _pass="$(openssl rand -base64 16 | tr -d '=/+')"
            _body="$(python3 -c "
import json
print(json.dumps({
    'email':               '${username}@${_domain}',
    'login_name':          '${username}',
    'must_change_password': False,
    'password':            '$_pass',
    'source_id':           0,
    'username':            '${username}',
}))")"
            _code="$(curl -sk -o /dev/null -w '%{http_code}' \
                -X POST "$FORGEJO_URL/api/v1/admin/users" \
                -H "Authorization: token $ADMIN_TOKEN" \
                -H "Content-Type: application/json" \
                -d "$_body" || true)"
            if [[ "$_code" == "201" ]]; then
                info "    ✓ user created (email: ${username}@${_domain})"
            else
                warn "    ✗ failed to create user (HTTP $_code)"
                REGISTER_FAILED+=("$username")
                continue
            fi
        elif [[ "$_status" == "200" ]]; then
            info "    user already exists"
        else
            warn "    ✗ user lookup returned HTTP $_status"
            REGISTER_FAILED+=("$username")
            continue
        fi

        # Register public key
        _key_body="$(python3 -c "
import json, sys
key = open('$pubkey').read().strip()
print(json.dumps({
    'key':       key,
    'read_only': False,
    'title':     '${username}-$(date +%Y%m%d)',
}))")"
        _kcode="$(curl -sk -o /dev/null -w '%{http_code}' \
            -X POST "$FORGEJO_URL/api/v1/admin/users/$username/keys" \
            -H "Authorization: token $ADMIN_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$_key_body" || true)"

        if [[ "$_kcode" == "201" ]]; then
            info "    ✓ SSH key registered"
        elif [[ "$_kcode" == "422" ]]; then
            info "    key already registered"
        else
            warn "    ✗ key registration failed (HTTP $_kcode)"
            REGISTER_FAILED+=("$username")
        fi
    done
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
header "Batch complete"
echo

for i in "${!USERNAMES[@]}"; do
    username="${USERNAMES[$i]}"
    pubkey="${PUBKEY_FILES[$i]}"
    cert="${CERT_FILES[$i]}"
    auto="${IS_AUTO_GENERATED[$i]}"

    if [[ -z "$pubkey" ]]; then
        printf "  ✗ %-20s skipped (invalid key source)\n" "$username"
    elif [[ -z "$cert" ]]; then
        printf "  ✗ %-20s signing failed\n" "$username"
    else
        fp="$(ssh-keygen -l -f "$cert" 2>/dev/null | awk '{print $2, $4}')"
        printf "  ✓ %-20s %s\n" "$username" "$fp"
        echo "       cert: $cert"
        if [[ "$auto" == "true" ]]; then
            echo "       key:  ${cert%-cert.pub}  ← send to user via secure channel"
        fi
    fi
done

echo
[[ ${#SIGN_FAILED[@]} -eq 0 ]]    || warn "Signing failed for: ${SIGN_FAILED[*]}"
if $REGISTER; then
    [[ ${#REGISTER_FAILED[@]} -eq 0 ]] || warn "Registration failed for: ${REGISTER_FAILED[*]}"
fi

echo
echo "  Each user needs:"
echo "    *-cert.pub  → place as ~/.ssh/<keyname>-cert.pub alongside their private key"
if [[ "${IS_AUTO_GENERATED[*]:-}" == *true* ]]; then
    echo "    id_ed25519  → send private key to user via secure channel (e.g. encrypted email)"
fi
$REGISTER && echo "  (Public keys registered in Forgejo — users can clone immediately after receiving cert)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
