#!/usr/bin/env bash
# sign-user-key.sh — Issue an SSH certificate for one or more Forgejo users.
#
# Single-user mode:
#   ./sign-user-key.sh <forgejo-username> <user-public-key-file> [options]
#
# Batch mode:
#   ./sign-user-key.sh --batch <csv-file> [options]
#
# CSV format (one user per line; blank lines and # comments ignored;
#             optional header "username,key" is skipped):
#   username
#   username,/path/to/key.pub
#   username,ssh-ed25519 AAAA...
#   (no key column → ed25519 keypair is auto-generated for that user)
#
# Options (both modes):
#   --forgejo-url URL   Forgejo base URL (default: https://<terraform output ip>)
#   --admin-token TOK   Forgejo admin API token (default: auto-generated via SSH)
#   --no-register       Sign cert(s) only; skip Forgejo user/key registration
#   --web-password      Derive a deterministic password from the user's Ed25519 key and set
#                       it in Forgejo, enabling web UI login. Requires Ed25519 keys.
#                       Password is tied to the instance IP; rerun after weekly rotation.
#   --private-key FILE  Ed25519 private key for web password derivation. In single-user mode,
#                       defaults to stripping .pub from the public key filename.
#
# Batch-only options:
#   --output-dir DIR    Write keys and certs here (default: ./keys)
#
# Environment overrides: FORGEJO_URL, FORGEJO_ADMIN_TOKEN, ADMIN_SSH_KEY, CERT_VALIDITY
#
# Requires:
#   - Yubikey with SSH CA key in PIV slot 9d (generated by setup.sh)
#   - ca.pub (SSH-format CA public key, written by setup.sh)
#   - .ykcs11_lib (PKCS#11 library path, written by setup.sh)
#
# Single-user produces: <user-pubkey-file>-cert.pub
# Batch produces:       keys/<username>/{id_ed25519,id_ed25519.pub,id_ed25519-cert.pub}
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"
info()   { echo -e "${GREEN}[sign]${NC} $*"; }
warn()   { echo -e "${YELLOW}[sign]${NC} $*"; }
error()  { echo -e "${RED}[sign]${NC} $*" >&2; exit 1; }
header() { echo -e "${CYAN}[sign]${NC} $*"; }

# ── Common prerequisites ───────────────────────────────────────────────────────
[ -f ca.pub ]      || error "ca.pub not found. Run setup.sh first."
[ -f .ykcs11_lib ] || error ".ykcs11_lib not found. Run setup.sh first."

PKCS11_LIB="$(cat .ykcs11_lib)"
[ -f "$PKCS11_LIB" ] || error "PKCS#11 library not found: $PKCS11_LIB"
ykman info &>/dev/null || error "No Yubikey detected. Connect your Yubikey and try again."

VALIDITY="${CERT_VALIDITY:-+365d}"

# ── Shared helpers ────────────────────────────────────────────────────────────

# Forgejo ≥7.0 requires explicit token scopes; enumerate all admin scopes so the
# generated token can create users, register keys, and patch passwords.
_FORGEJO_ADMIN_SCOPES="read:activitypub,write:activitypub,read:admin,write:admin,read:issue,write:issue,read:misc,write:misc,read:notification,write:notification,read:organization,write:organization,read:package,write:package,read:repository,write:repository,read:user,write:user"

# Resolve Forgejo URL and admin token into FORGEJO_URL and ADMIN_TOKEN globals.
resolve_forgejo_credentials() {
    if [[ -z "$FORGEJO_URL" ]]; then
        local _ip=""
        if command -v terraform &>/dev/null; then
            # Try last-used provider's terraform dir first
            local _last_provider=""
            [[ -f "$SCRIPT_DIR/.last-provider" ]] && _last_provider="$(cat "$SCRIPT_DIR/.last-provider" | tr -d '[:space:]')"
            local _tf_dirs=("$SCRIPT_DIR/terraform/vultr")
            [[ -n "$_last_provider" ]] && \
                _tf_dirs=("$SCRIPT_DIR/terraform/$_last_provider" "$SCRIPT_DIR/terraform/vultr")
            local _ipv6=""
            for _dir in "${_tf_dirs[@]}"; do
                [[ -d "$_dir" ]] || continue
                _ip="$(cd "$_dir" && terraform output -raw public_ipv4 2>/dev/null || true)"
                _ipv6="$(cd "$_dir" && terraform output -raw public_ipv6 2>/dev/null || true)"
                [[ -n "$_ip" || -n "$_ipv6" ]] && break
            done
        fi
        if [[ -n "$_ip" ]]; then
            FORGEJO_URL="https://${_ip}"
        elif [[ -n "$_ipv6" ]]; then
            FORGEJO_URL="https://[${_ipv6}]"
        else
            error "Cannot determine Forgejo URL. Pass --forgejo-url URL or set FORGEJO_URL."
        fi
        info "Forgejo URL (from Terraform): $FORGEJO_URL"
    fi

    if [[ -z "$ADMIN_TOKEN" ]]; then
        local _ip="${FORGEJO_URL#https://}"; _ip="${_ip#http://}"; _ip="${_ip%%/*}"
        _ip="${_ip#[}"; _ip="${_ip%]}"   # strip brackets from IPv6 literals
        local _admin_user="gitadmin"
        if [[ -f "$SCRIPT_DIR/.vault.token" ]]; then
            export VAULT_ADDR="http://127.0.0.1:8200"
            export VAULT_TOKEN="$(cat "$SCRIPT_DIR/.vault.token")"
            if vault status &>/dev/null 2>&1; then
                local _vu
                _vu="$(vault kv get -field=forgejo_admin_user secret/forgejo/deploy 2>/dev/null || true)"
                [[ -n "$_vu" ]] && _admin_user="$_vu"
            fi
        fi
        local _ssh_key="${ADMIN_SSH_KEY:-$HOME/.ssh/id_ed25519}"
        local _kh="$SCRIPT_DIR/known_hosts.deploy"
        local _ssh_opts="-i $_ssh_key -o CanonicalizeHostname=no -o ConnectTimeout=15 -o BatchMode=yes"
        [[ -f "$_kh" ]] \
            && _ssh_opts="$_ssh_opts -o UserKnownHostsFile=$_kh -o StrictHostKeyChecking=yes" \
            || _ssh_opts="$_ssh_opts -o StrictHostKeyChecking=no"
        # SSH as deploy (docker group member); root login is disabled after hardening.
        # deploy has docker group access so it can run docker exec without sudo.
        info "Generating admin API token via SSH as deploy@$_ip (admin user: $_admin_user)..."
        local _tok_err
        _tok_err="$(mktemp)"
        # Try with --token-expiry 1h first; fall back without it (not all versions support it).
        # In debug mode: tee stderr live to terminal so Forgejo errors are immediately visible.
        # shellcheck disable=SC2086
        ADMIN_TOKEN="$(ssh $_ssh_opts "deploy@$_ip" \
            "docker exec -u git forgejo /usr/local/bin/forgejo admin user \
             generate-access-token --username $_admin_user \
             --token-name sign-$(date +%s) --token-expiry 1h --scopes $_FORGEJO_ADMIN_SCOPES --raw" \
            2> >(if [[ "${DEBUG}" == 1 ]]; then tee -a "$_tok_err" >&2; else cat >> "$_tok_err"; fi) || true)"
        ADMIN_TOKEN="$(printf '%s\n' "$ADMIN_TOKEN" | tail -1 | tr -d '[:space:]')"
        if [[ -z "$ADMIN_TOKEN" ]]; then
            # shellcheck disable=SC2086
            ADMIN_TOKEN="$(ssh $_ssh_opts "deploy@$_ip" \
                "docker exec -u git forgejo /usr/local/bin/forgejo admin user \
                 generate-access-token --username $_admin_user \
                 --token-name sign-$(date +%s) --scopes $_FORGEJO_ADMIN_SCOPES --raw" \
                2> >(if [[ "${DEBUG}" == 1 ]]; then tee -a "$_tok_err" >&2; else cat >> "$_tok_err"; fi) || true)"
            ADMIN_TOKEN="$(printf '%s\n' "$ADMIN_TOKEN" | tail -1 | tr -d '[:space:]')"
        fi
        if [[ -z "$ADMIN_TOKEN" ]]; then
            local _tok_err_msg
            _tok_err_msg="$(head -3 "$_tok_err" 2>/dev/null)"
            rm -f "$_tok_err"
            [[ -n "$_tok_err_msg" ]] && warn "Remote error: $_tok_err_msg"
            error "Could not obtain admin token. Pass --admin-token TOKEN or set FORGEJO_ADMIN_TOKEN."
        fi
        rm -f "$_tok_err"
        info "Admin token obtained."
    fi
}

# Create user (if absent) and register their public key in Forgejo.
# Args: username pubkey_file
register_user() {
    local username="$1" pubkey="$2"
    local _domain="${FORGEJO_URL#https://}"; _domain="${_domain#http://}"; _domain="${_domain%%/*}"

    info "  ── $username"

    local _status
    _status="$(curl -sk -o /dev/null -w '%{http_code}' \
        -H "Authorization: token $ADMIN_TOKEN" \
        "$FORGEJO_URL/api/v1/users/$username" || true)"

    if [[ "$_status" == "404" ]]; then
        local _pass _body _code
        _pass="$(openssl rand -base64 16 | tr -d '=/+')"
        _body="$(python3 -c "
import json
print(json.dumps({
    'email':                '${username}@${_domain}',
    'login_name':           '${username}',
    'must_change_password': False,
    'password':             '$_pass',
    'source_id':            0,
    'username':             '${username}',
}))")"
        _code="$(curl -sk -o /dev/null -w '%{http_code}' \
            -X POST "$FORGEJO_URL/api/v1/admin/users" \
            -H "Authorization: token $ADMIN_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$_body" || true)"
        if [[ "$_code" == "201" ]]; then
            info "    ✓ user created (email: ${username}@${_domain})"
        else
            warn "    ✗ failed to create user (HTTP $_code)"
            return 1
        fi
    elif [[ "$_status" == "200" ]]; then
        info "    user already exists"
    else
        warn "    ✗ user lookup returned HTTP $_status"
        return 1
    fi

    local _key_body _kcode
    _key_body="$(python3 -c "
import json
key = open('$pubkey').read().strip()
print(json.dumps({
    'key':       key,
    'read_only': False,
    'title':     '${username}-$(date +%Y%m%d)',
}))")"
    _kcode="$(curl -sk -o /dev/null -w '%{http_code}' \
        -X POST "$FORGEJO_URL/api/v1/admin/users/$username/keys" \
        -H "Authorization: token $ADMIN_TOKEN" \
        -H "Content-Type: application/json" \
        -d "$_key_body" || true)"
    if [[ "$_kcode" == "201" ]]; then
        info "    ✓ SSH key registered"
    elif [[ "$_kcode" == "422" ]]; then
        info "    key already registered"
    else
        warn "    ✗ key registration failed (HTTP $_kcode)"
        return 1
    fi
}

# Returns exit 0 if the public key file is Ed25519, exit 1 otherwise.
_require_ed25519_pubkey() {
    local _type; _type="$(awk '{print $1}' "$1" 2>/dev/null)"
    [[ "$_type" == "ssh-ed25519" ]]
}

# Load the PKCS#11 CA key into ssh-agent with a single PIN prompt so batch
# signings reuse the cached key via ssh-keygen -U instead of prompting per user.
# On success sets _YUBIKEY_IN_AGENT=true.  Falls back gracefully if the agent is
# unavailable or the PIN is wrong.
#
# Security note: the PIN is passed to ssh-add's environment as _YKPIN for the
# duration of that one execve() call.  It is briefly visible to same-uid processes
# via /proc/PID/environ.  Acceptable on a local admin workstation.
_YUBIKEY_IN_AGENT=false
_yubikey_agent_load() {
    if [[ -z "${SSH_AUTH_SOCK:-}" ]]; then
        warn "No SSH agent running (SSH_AUTH_SOCK unset); PIN will be prompted per signing."
        return
    fi
    printf "YubiKey PIN: "
    { set +x; } 2>/dev/null
    read -r -s _ypin
    echo
    local _ap
    _ap="$(mktemp)"
    chmod 700 "$_ap"
    # The askpass script reads the PIN from _YKPIN which ssh-add inherits.
    printf '#!/bin/sh\nprintf "%%s" "$_YKPIN"\n' > "$_ap"
    local _rc=0
    # set +x already active above; keep it so the PIN assignment is not traced.
    _YKPIN="$_ypin" DISPLAY="${DISPLAY:-:0}" SSH_ASKPASS_REQUIRE=force SSH_ASKPASS="$_ap" \
        ssh-add -s "$PKCS11_LIB" < /dev/null 2>&1 || _rc=$?
    rm -f "$_ap"
    unset _ypin
    [[ "${DEBUG}" == 1 ]] && set -x
    if [[ $_rc -eq 0 ]]; then
        _YUBIKEY_IN_AGENT=true
    else
        warn "Failed to load YubiKey into agent (wrong PIN? PIV locks after 3 wrong attempts)."
        warn "Falling back to per-signing PIN prompt."
    fi
}

_yubikey_agent_unload() {
    [[ "$_YUBIKEY_IN_AGENT" == true ]] || return 0
    ssh-add -e "$PKCS11_LIB" 2>/dev/null || true
    _YUBIKEY_IN_AGENT=false
}

# Derive a deterministic web UI password from an Ed25519 private key and an instance IP.
# Challenge: "webapp-password:<instance_ip>:v1" — tied to the instance lifetime.
# After weekly rotation the instance IP changes; re-run sign-user-key.sh --web-password
# to push the new password to the new instance.
#
# SECURITY: The caller MUST suppress set -x before calling AND before capturing the output
# in a variable, to prevent the password from appearing in the execution trace.
# Args: privkey_path instance_ip
# Outputs: 32-char URL-safe base64 password on stdout (no trailing newline)
derive_web_password() {
    local privkey="$1" instance_ip="$2"
    local challenge="webapp-password:${instance_ip}:v1"
    printf '%s' "$challenge" \
        | ssh-keygen -Y sign -f "$privkey" -n password-derivation 2>/dev/null \
        | grep -v '^-----' \
        | base64 -d \
        | sha256sum \
        | python3 -c "import sys, base64
d = bytes.fromhex(sys.stdin.read().split()[0])
print(base64.urlsafe_b64encode(d[:24]).decode().rstrip('='), end='')"
}

# Set a user's web UI password via the Forgejo admin API.
# SECURITY: The caller MUST suppress set -x; a temp file holds the plaintext password.
# Args: username web_password
# Returns: 0 on HTTP 200, 1 otherwise.
set_web_password() {
    local username="$1" password="$2"
    local _tmp; _tmp="$(mktemp)"
    chmod 600 "$_tmp"
    python3 -c "
import json, sys
print(json.dumps({
    'login_name':           sys.argv[1],
    'must_change_password': False,
    'password':             sys.argv[2],
    'source_id':            0,
}))" "$username" "$password" > "$_tmp"
    local _code
    _code="$(curl -sk -o /dev/null -w '%{http_code}' \
        -X PATCH "$FORGEJO_URL/api/v1/admin/users/$username" \
        -H "Authorization: token $ADMIN_TOKEN" \
        -H "Content-Type: application/json" \
        --data-binary "@$_tmp" || true)"
    rm -f "$_tmp"
    [[ "$_code" == "200" ]]
}

# ── Single-user mode ──────────────────────────────────────────────────────────
if [[ "${1:-}" != "--batch" ]]; then
    [ "$#" -ge 2 ] || error "Usage: $0 <forgejo-username> <user-public-key-file> [--forgejo-url URL] [--admin-token TOKEN] [--no-register] [--web-password] [--private-key FILE]
       $0 --batch <csv-file> [--output-dir DIR] [--forgejo-url URL] [--admin-token TOKEN] [--no-register] [--web-password]"
    USERNAME="$1"
    USER_PUBKEY="$2"
    shift 2
    [ -f "$USER_PUBKEY" ] || error "Public key file not found: $USER_PUBKEY"

    FORGEJO_URL="${FORGEJO_URL:-}"
    ADMIN_TOKEN="${FORGEJO_ADMIN_TOKEN:-}"
    REGISTER=true
    WEB_PASSWORD=false
    PRIVATE_KEY=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --forgejo-url)  FORGEJO_URL="$2"; shift 2 ;;
            --admin-token)  ADMIN_TOKEN="$2"; shift 2 ;;
            --no-register)  REGISTER=false; shift ;;
            --web-password) WEB_PASSWORD=true; shift ;;
            --private-key)  PRIVATE_KEY="$2"; shift 2 ;;
            --debug)        DEBUG=1; shift ;;
            *) error "Unknown option: $1" ;;
        esac
    done
    [[ "${DEBUG}" == 1 ]] && { export DEBUG; set -x; }

    info "Signing public key for Forgejo user '$USERNAME' (validity: $VALIDITY)"
    info "Principal: git (Unix login user)"
    info "Key file:  $USER_PUBKEY"
    echo

    info "Waiting for Yubikey touch/PIN (you may be prompted up to twice)..."
    ssh-keygen \
        -s ca.pub \
        -D "$PKCS11_LIB" \
        -I "${USERNAME}@forgejo" \
        -n "git" \
        -V "$VALIDITY" \
        "$USER_PUBKEY"

    CERT_FILE="${USER_PUBKEY%.*}-cert.pub"
    [ -f "$CERT_FILE" ] || CERT_FILE="${USER_PUBKEY}-cert.pub"
    [ -f "$CERT_FILE" ] || error "Certificate file not found after signing. Check ssh-keygen output above."

    if $REGISTER || $WEB_PASSWORD; then
        echo
        resolve_forgejo_credentials
    fi

    if $REGISTER; then
        echo
        header "Registering in Forgejo ($FORGEJO_URL)..."
        echo
        register_user "$USERNAME" "$USER_PUBKEY" || true
    fi

    WEB_PASS=""
    _instance_ip=""
    if $WEB_PASSWORD; then
        if [[ -z "$PRIVATE_KEY" ]]; then
            _try="${USER_PUBKEY%.pub}"
            [[ "$_try" != "$USER_PUBKEY" && -f "$_try" ]] \
                && PRIVATE_KEY="$_try" \
                || error "--web-password: private key not found alongside pubkey. Pass --private-key PATH."
        fi
        [[ -f "$PRIVATE_KEY" ]] || error "--web-password: private key file not found: $PRIVATE_KEY"
        if _require_ed25519_pubkey "$USER_PUBKEY"; then
            _instance_ip="${FORGEJO_URL#https://}"; _instance_ip="${_instance_ip#http://}"
            _instance_ip="${_instance_ip%%/*}"; _instance_ip="${_instance_ip#[}"; _instance_ip="${_instance_ip%]}"
            echo
            info "Deriving web UI password from Ed25519 key (instance: ${_instance_ip})..."
            { set +x; } 2>/dev/null
            WEB_PASS="$(derive_web_password "$PRIVATE_KEY" "$_instance_ip")"
            if set_web_password "$USERNAME" "$WEB_PASS"; then
                info "  ✓ web UI password set in Forgejo"
            else
                warn "  ✗ web UI password API call failed; skipping"
                WEB_PASS=""
            fi
            [[ "${DEBUG}" == 1 ]] && set -x
        else
            warn "--web-password: not an Ed25519 key; password derivation requires Ed25519. Skipping."
        fi
    fi

    echo
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    info "Certificate issued: $CERT_FILE"
    echo "  Fingerprint: $(ssh-keygen -l -f "$CERT_FILE")"
    echo
    echo "  Instructions for '$USERNAME':"
    echo "    1. Place $CERT_FILE alongside your private key"
    echo "       (e.g. ~/.ssh/id_ed25519-cert.pub if key is ~/.ssh/id_ed25519)"
    echo "       SSH picks it up automatically — no config change needed."
    if $REGISTER; then
        echo "    2. Public key registered in Forgejo — ready to clone."
    else
        echo "    2. Register the raw public key in Forgejo"
        echo "       (Settings → SSH / GPG Keys → Add Key)."
    fi
    echo "    3. Clone with:  git clone ssh://git@<ip>:2222/<username>/<repo>.git"
    if [[ -n "$WEB_PASS" ]]; then
        { set +x; } 2>/dev/null
        echo
        echo "  Web UI access:"
        printf "    Password:  %s\n" "$WEB_PASS"
        printf "    Login URL: %s\n" "$FORGEJO_URL"
        echo
        echo "  $USERNAME can re-derive this password with:"
        printf "    CHALLENGE=\"webapp-password:%s:v1\"\n" "$_instance_ip"
        cat << 'REDERIVE'
    echo -n "$CHALLENGE" | ssh-keygen -Y sign -f ~/.ssh/id_ed25519 \
        -n password-derivation 2>/dev/null | grep -v '^-----' | base64 -d | \
        sha256sum | python3 -c "import sys, base64; d=bytes.fromhex(sys.stdin.read().split()[0]); \
        print(base64.urlsafe_b64encode(d[:24]).decode().rstrip('='), end='')"
REDERIVE
        [[ "${DEBUG}" == 1 ]] && set -x
    fi
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    exit 0
fi

# ── Batch mode ────────────────────────────────────────────────────────────────
shift  # consume --batch
[ $# -ge 1 ] || error "Usage: $0 --batch <csv-file> [options]"
BATCH_CSV="$1"; shift
[ -f "$BATCH_CSV" ] || error "CSV file not found: $BATCH_CSV"

OUTPUT_DIR="./keys"
FORGEJO_URL="${FORGEJO_URL:-}"
ADMIN_TOKEN="${FORGEJO_ADMIN_TOKEN:-}"
REGISTER=true
WEB_PASSWORD=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output-dir)   OUTPUT_DIR="$2"; shift 2 ;;
        --forgejo-url)  FORGEJO_URL="$2"; shift 2 ;;
        --admin-token)  ADMIN_TOKEN="$2"; shift 2 ;;
        --no-register)  REGISTER=false; shift ;;
        --web-password) WEB_PASSWORD=true; shift ;;
        --debug)        DEBUG=1; shift ;;
        *) error "Unknown option: $1" ;;
    esac
done
[[ "${DEBUG}" == 1 ]] && { export DEBUG; set -x; }

mkdir -p "$OUTPUT_DIR"

# ── Parse CSV ─────────────────────────────────────────────────────────────────
header "Parsing $BATCH_CSV..."

declare -a USERNAMES=()
declare -a KEY_SOURCES=()

while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line//$'\r'/}"                    # strip Windows CR
    [[ -z "$line" || "$line" == \#* ]] && continue

    username="${line%%,*}"
    username="${username//[[:space:]]/}"      # strip all whitespace
    [[ -z "$username" || "${username,,}" == "username" ]] && continue

    if [[ "$line" == *,* ]]; then
        key_col="${line#*,}"
        # strip leading and trailing whitespace
        key_col="${key_col#"${key_col%%[![:space:]]*}"}"
        key_col="${key_col%"${key_col##*[![:space:]]}"}"
    else
        key_col=""
    fi

    USERNAMES+=("$username")
    KEY_SOURCES+=("$key_col")
done < "$BATCH_CSV"

[ ${#USERNAMES[@]} -gt 0 ] || error "No users found in $BATCH_CSV"
info "Found ${#USERNAMES[@]} user(s): ${USERNAMES[*]}"
echo

# ── Resolve or generate public keys ───────────────────────────────────────────
header "Preparing public keys..."

declare -a PUBKEY_FILES=()
declare -a IS_AUTO_GENERATED=()

for i in "${!USERNAMES[@]}"; do
    username="${USERNAMES[$i]}"
    key_src="${KEY_SOURCES[$i]}"
    user_dir="$OUTPUT_DIR/$username"
    mkdir -p "$user_dir"

    if [[ -z "$key_src" ]]; then
        # Auto-generate ed25519 keypair
        priv="$user_dir/id_ed25519"
        pub="${priv}.pub"
        if [[ -f "$pub" ]]; then
            warn "  $username: reusing existing key at $pub"
        else
            ssh-keygen -t ed25519 -N "" -C "${username}@forgejo" -f "$priv" -q
            chmod 600 "$priv"
            info "  $username: generated ed25519 keypair → $priv"
        fi
        PUBKEY_FILES+=("$pub")
        IS_AUTO_GENERATED+=(true)

    elif [[ "$key_src" == ssh-* || "$key_src" == ecdsa-* || "$key_src" == sk-* ]]; then
        # Inline SSH public key string
        pub="$user_dir/authorized_key.pub"
        echo "$key_src" > "$pub"
        info "  $username: using provided SSH public key"
        PUBKEY_FILES+=("$pub")
        IS_AUTO_GENERATED+=(false)

    elif [[ -f "$key_src" ]]; then
        # Path to an existing .pub file
        info "  $username: using key file $key_src"
        PUBKEY_FILES+=("$key_src")
        IS_AUTO_GENERATED+=(false)

    else
        warn "  $username: key source not found or unrecognized: '$key_src' — skipping"
        PUBKEY_FILES+=("")
        IS_AUTO_GENERATED+=(false)
    fi
done

echo

# ── Sign all keys with Yubikey ────────────────────────────────────────────────
VALID_COUNT=0
for pf in "${PUBKEY_FILES[@]}"; do [[ -n "$pf" ]] && VALID_COUNT=$((VALID_COUNT + 1)); done

header "Signing $VALID_COUNT key(s) with Yubikey (validity: $VALIDITY)"
_yubikey_agent_load
if [[ "$_YUBIKEY_IN_AGENT" == true ]]; then
    info "PIN accepted. Touch the Yubikey when prompted (cached 15 s between signings)."
    _sign_extra=(-U)
else
    warn "Touch is cached for 15 s — you may need to touch the Yubikey multiple times."
    _sign_extra=(-D "$PKCS11_LIB")
fi
echo

declare -a CERT_FILES=()
declare -a SIGN_FAILED=()

for i in "${!USERNAMES[@]}"; do
    username="${USERNAMES[$i]}"
    pubkey="${PUBKEY_FILES[$i]}"

    if [[ -z "$pubkey" ]]; then
        CERT_FILES+=("")
        continue
    fi

    user_dir="$OUTPUT_DIR/$username"
    pub_basename="$(basename "$pubkey")"
    local_pub="$user_dir/$pub_basename"

    # Ensure the pubkey lives in user_dir so the cert is written there
    [[ "$pubkey" != "$local_pub" ]] && cp "$pubkey" "$local_pub"

    info "  Signing '$username'..."
    if ssh-keygen \
            -s ca.pub \
            "${_sign_extra[@]}" \
            -I "${username}@forgejo" \
            -n "git" \
            -V "$VALIDITY" \
            "$local_pub" 2>&1; then

        # ssh-keygen appends -cert.pub after stripping the existing extension
        expected="${local_pub%.*}-cert.pub"
        [[ -f "$expected" ]] || expected="${local_pub}-cert.pub"

        if [[ -f "$expected" ]]; then
            CERT_FILES+=("$expected")
            info "  ✓ $username → $(basename "$expected")"
        else
            warn "  ✗ $username: cert not found after signing"
            CERT_FILES+=("")
            SIGN_FAILED+=("$username")
        fi
    else
        warn "  ✗ $username: ssh-keygen failed"
        CERT_FILES+=("")
        SIGN_FAILED+=("$username")
    fi
done

_yubikey_agent_unload

echo

# ── Register in Forgejo and set web passwords ─────────────────────────────────
declare -a REGISTER_FAILED=()
declare -a WEB_PASSES=()
_instance_ip=""

if $REGISTER || $WEB_PASSWORD; then
    resolve_forgejo_credentials
    echo
    header "Registering in Forgejo ($FORGEJO_URL)..."
    echo

    if $WEB_PASSWORD; then
        _instance_ip="${FORGEJO_URL#https://}"; _instance_ip="${_instance_ip#http://}"
        _instance_ip="${_instance_ip%%/*}"; _instance_ip="${_instance_ip#[}"; _instance_ip="${_instance_ip%]}"
    fi

    for i in "${!USERNAMES[@]}"; do
        username="${USERNAMES[$i]}"
        pubkey="${PUBKEY_FILES[$i]}"
        cert="${CERT_FILES[$i]}"

        [[ -n "$pubkey" && -n "$cert" ]] || continue

        if $REGISTER; then
            register_user "$username" "$pubkey" || REGISTER_FAILED+=("$username")
        fi

        WEB_PASSES[$i]=""
        if $WEB_PASSWORD; then
            _priv=""
            if [[ "${IS_AUTO_GENERATED[$i]}" == "true" ]]; then
                _priv="$OUTPUT_DIR/$username/id_ed25519"
            else
                _try="${pubkey%.pub}"
                [[ "$_try" != "$pubkey" && -f "$_try" ]] && _priv="$_try"
            fi
            if [[ -z "$_priv" || ! -f "$_priv" ]]; then
                warn "    ✗ web password skipped (no private key file found)"
            elif ! _require_ed25519_pubkey "$pubkey"; then
                warn "    ✗ web password skipped (key type is not Ed25519)"
            else
                { set +x; } 2>/dev/null
                _wp="$(derive_web_password "$_priv" "$_instance_ip")"
                if set_web_password "$username" "$_wp"; then
                    info "    ✓ web UI password set"
                    WEB_PASSES[$i]="$_wp"
                else
                    warn "    ✗ web UI password API call failed"
                fi
                [[ "${DEBUG}" == 1 ]] && set -x
            fi
        fi
    done
fi

# ── Write SSH client config ────────────────────────────────────────────────────
# Resolve HostName from FORGEJO_URL if already known; fall back to Terraform
# output so config files are written even when --no-register is passed.
_config_host=""
if [[ -n "${FORGEJO_URL:-}" ]]; then
    _config_host="${FORGEJO_URL#https://}"; _config_host="${_config_host#http://}"
    _config_host="${_config_host%%/*}"; _config_host="${_config_host#[}"; _config_host="${_config_host%]}"
elif command -v terraform &>/dev/null; then
    _last_provider=""; [[ -f "$SCRIPT_DIR/.last-provider" ]] && \
        _last_provider="$(tr -d '[:space:]' < "$SCRIPT_DIR/.last-provider")"
    _ch_dirs=("$SCRIPT_DIR/terraform/vultr")
    [[ -n "$_last_provider" ]] && \
        _ch_dirs=("$SCRIPT_DIR/terraform/$_last_provider" "$SCRIPT_DIR/terraform/vultr")
    for _ch_dir in "${_ch_dirs[@]}"; do
        [[ -d "$_ch_dir" ]] || continue
        _ch="$(cd "$_ch_dir" && terraform output -raw public_ipv4 2>/dev/null || true)"
        [[ -z "$_ch" ]] && _ch="$(cd "$_ch_dir" && terraform output -raw public_ipv6 2>/dev/null || true)"
        [[ -n "$_ch" ]] && { _config_host="$_ch"; break; }
    done
fi

declare -a CONFIG_FILES=()

if [[ -z "$_config_host" ]]; then
    warn "Instance IP unknown — SSH config files skipped. Pass --forgejo-url to generate them."
    for i in "${!USERNAMES[@]}"; do CONFIG_FILES+=(""); done
else
    echo
    header "Writing SSH client configs (HostName: $_config_host)..."
    echo
    for i in "${!USERNAMES[@]}"; do
        cert="${CERT_FILES[$i]:-}"
        username="${USERNAMES[$i]}"
        if [[ -z "$cert" ]]; then
            CONFIG_FILES+=("")
            continue
        fi
        # Derive IdentityFile from the cert name: strip -cert.pub suffix.
        # After copying the folder to ~/.ssh/ the private key lives at this path.
        cert_base="$(basename "$cert")"
        keyname="${cert_base%-cert.pub}"
        config_out="$OUTPUT_DIR/$username/config"
        cat > "$config_out" <<EOF
# Forgejo instance: $_config_host
# ─────────────────────────────────────────────────────────────────────────────
# Clone a repository:
#   git clone git@forgejo:$username/<repo>.git
#
# Re-derive your Forgejo web UI password (rerun after each weekly rotation):
#   CHALLENGE="webapp-password:$_config_host:v1"
#   echo -n "\$CHALLENGE" | ssh-keygen -Y sign -f ~/.ssh/$keyname \\
#       -n password-derivation 2>/dev/null | grep -v '^\-----' | base64 -d | \\
#       sha256sum | python3 -c "import sys, base64; \\
#       d=bytes.fromhex(sys.stdin.read().split()[0]); \\
#       print(base64.urlsafe_b64encode(d[:24]).decode().rstrip('='), end='')"
# ─────────────────────────────────────────────────────────────────────────────
Host forgejo
    HostName $_config_host
    Port 2222
    User git
    IdentityFile ~/.ssh/$keyname
    CertificateFile ~/.ssh/$cert_base
EOF
        chmod 600 "$config_out"
        CONFIG_FILES+=("$config_out")
        info "  ✓ $username → $config_out"
    done
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
header "Batch complete"
echo

for i in "${!USERNAMES[@]}"; do
    username="${USERNAMES[$i]}"
    pubkey="${PUBKEY_FILES[$i]}"
    cert="${CERT_FILES[$i]}"
    auto="${IS_AUTO_GENERATED[$i]}"

    if [[ -z "$pubkey" ]]; then
        printf "  ✗ %-20s skipped (invalid key source)\n" "$username"
    elif [[ -z "$cert" ]]; then
        printf "  ✗ %-20s signing failed\n" "$username"
    else
        fp="$(ssh-keygen -l -f "$cert" 2>/dev/null | awk '{print $2, $4}')"
        printf "  ✓ %-20s %s\n" "$username" "$fp"
        echo "       cert: $cert"
        if [[ "$auto" == "true" ]]; then
            echo "       key:  ${cert%-cert.pub}  ← send to user via secure channel"
        fi
        if [[ -n "${CONFIG_FILES[$i]:-}" ]]; then
            echo "       conf: ${CONFIG_FILES[$i]}"
        fi
        if $WEB_PASSWORD && [[ -n "${WEB_PASSES[$i]:-}" ]]; then
            { set +x; } 2>/dev/null
            printf "       web:  %s  ← Forgejo web UI password\n" "${WEB_PASSES[$i]}"
            [[ "${DEBUG}" == 1 ]] && set -x
        fi
    fi
done

echo
[[ ${#SIGN_FAILED[@]} -eq 0 ]]    || warn "Signing failed for: ${SIGN_FAILED[*]}"
if $REGISTER; then
    [[ ${#REGISTER_FAILED[@]} -eq 0 ]] || warn "Registration failed for: ${REGISTER_FAILED[*]}"
fi

echo
echo "  Each user needs:"
if [[ -n "${_config_host:-}" ]]; then
    echo "    Copy $OUTPUT_DIR/<username>/ to ~/.ssh/ (merge config into existing if needed)."
    echo "    Then clone with: git clone git@forgejo:<username>/<repo>.git"
else
    echo "    *-cert.pub  → place as ~/.ssh/<keyname>-cert.pub alongside their private key"
fi
if [[ "${IS_AUTO_GENERATED[*]:-}" == *true* ]]; then
    echo "    id_ed25519  → send private key to user via secure channel (e.g. encrypted email)"
fi
$REGISTER && echo "  (Public keys registered in Forgejo — users can clone immediately after receiving cert)"
if $WEB_PASSWORD && [[ -n "${_instance_ip:-}" ]]; then
    echo
    echo "  Web UI password re-derivation (update INSTANCE_IP after a weekly rotation):"
    printf "    CHALLENGE=\"webapp-password:%s:v1\"\n" "$_instance_ip"
    cat << 'REDERIVE'
    echo -n "$CHALLENGE" | ssh-keygen -Y sign -f ~/.ssh/id_ed25519 \
        -n password-derivation 2>/dev/null | grep -v '^-----' | base64 -d | \
        sha256sum | python3 -c "import sys, base64; d=bytes.fromhex(sys.stdin.read().split()[0]); \
        print(base64.urlsafe_b64encode(d[:24]).decode().rstrip('='), end='')"
REDERIVE
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
