#!/usr/bin/env bash
# sign-user-key.sh — Issue an SSH certificate for a Forgejo user.
#
# Usage: ./sign-user-key.sh <forgejo-username> <user-public-key-file>
#
# Requires:
#   - Yubikey with SSH CA key in PIV slot 9d (generated by setup.sh)
#   - ca.pub (SSH-format CA public key, written by setup.sh)
#   - .ykcs11_lib  (PKCS#11 library path, written by setup.sh)
#
# The certificate principal (-n) is set to the Forgejo username.
# The user MUST also have their raw public key registered in Forgejo so
# Forgejo can map the SSH session to their account.
#
# Produces: <user-pubkey-file>-cert.pub
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[sign]${NC} $*"; }
error() { echo -e "${RED}[sign]${NC} $*" >&2; exit 1; }

# ── Validate arguments ────────────────────────────────────────────────────────
[ "$#" -eq 2 ] || error "Usage: $0 <forgejo-username> <user-public-key-file>"

USERNAME="$1"
USER_PUBKEY="$2"

[ -f "$USER_PUBKEY" ] || error "Public key file not found: $USER_PUBKEY"
[ -f ca.pub ]         || error "ca.pub not found. Run setup.sh first."
[ -f .ykcs11_lib ]    || error ".ykcs11_lib not found. Run setup.sh first."

PKCS11_LIB="$(cat .ykcs11_lib)"
[ -f "$PKCS11_LIB" ]  || error "PKCS#11 library not found: $PKCS11_LIB"

# ── Verify Yubikey is present ─────────────────────────────────────────────────
ykman info &>/dev/null || error "No Yubikey detected. Connect your Yubikey and try again."

# ── Validity period ───────────────────────────────────────────────────────────
VALIDITY="${CERT_VALIDITY:-+365d}"
info "Signing public key for Forgejo user '$USERNAME' (validity: $VALIDITY)"
# Principal must be 'git' (the Unix login user for all Forgejo SSH connections).
# The Forgejo user is identified by the registered base public key via
# AuthorizedKeysCommand, not by the cert principal.
info "Principal: git (Unix login user)"
info "Key file:  $USER_PUBKEY"
echo

# ── Sign with Yubikey via PKCS#11 ────────────────────────────────────────────
# -s ca.pub        : SSH-format public key identifying which PKCS#11 key to use
# -D PKCS11_LIB    : PKCS#11 library; private key stays on Yubikey
# -I identity      : certificate identity string (informational)
# -n principal     : must match Forgejo username for AuthorizedKeysCommand routing
# -V validity      : certificate validity window
#
# NOTE: If this fails with "pkcs11 not supported", your OpenSSH was built
# without PKCS#11 support. Install openssh-client from the distro package.
# Yubico docs reference: developers.yubico.com/PIV/Guides/SSH_user_certificates.html
info "Waiting for Yubikey touch/PIN (you may be prompted up to twice)..."
ssh-keygen \
    -s ca.pub \
    -D "$PKCS11_LIB" \
    -I "${USERNAME}@forgejo" \
    -n "git" \
    -V "$VALIDITY" \
    "$USER_PUBKEY"

CERT_FILE="${USER_PUBKEY%.*}-cert.pub"
if [ ! -f "$CERT_FILE" ]; then
    # ssh-keygen appends -cert.pub to the input filename
    CERT_FILE="${USER_PUBKEY}-cert.pub"
fi

[ -f "$CERT_FILE" ] || error "Certificate file not found after signing. Check ssh-keygen output above."

echo
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
info "Certificate issued: $CERT_FILE"
echo "  Fingerprint: $(ssh-keygen -l -f "$CERT_FILE")"
echo
echo "  Instructions for '$USERNAME':"
echo "    1. Place $CERT_FILE alongside your private key"
echo "       (e.g. ~/.ssh/id_ed25519-cert.pub if key is ~/.ssh/id_ed25519)"
echo "       SSH picks it up automatically — no config change needed."
echo "    2. Ensure your raw public key is registered in Forgejo"
echo "       (Settings → SSH / GPG Keys → Add Key)."
echo "    3. Clone with:  git clone git@\$DOMAIN:2222/user/repo.git"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
